pipeline{
  tools{
    maven 'Maven'
  }
  agent any
  stages {
    stage ('Initialize-new'){
      steps {
        sh '''
              echo "PATH = ${PATH}"
              echo "M2_HOME = ${M2_HOME)"
        '''
      }
    }

    stage ('Build-new'){
      steps{
        sh 'mvn clean package'
      }
    }
  
  }  
  
}
